import os

# --- Конфигурация ---
BOT_TOKEN = "8550474374:AAFIgrEaIYVNuZ2OIMOiiN0NekIzvdVEdaE"
MAX_TEAMS = 10
ADMIN_CHAT_ID = 817138654
TOURNAMENT_DATE = "25 ноября 2025"

# --- States для ConversationHandler ---
WAITING_FOR_PROMO = 0
CONFIRM_PROMO = 1
REGISTER_OPTION = 2
WAITING_FOR_CAPTAIN_CONFIRM = 3
WAITING_FOR_TEAM_NAME = 4
WAITING_FOR_MMR = 5
WAITING_FOR_SOLO_MMR = 8
ADMIN_ACTIONS = 10
WAITING_WINNER_SELECTION = 11

# Настройки данных
DATA_DIR = "data"
PROMOCODES_FILE = os.path.join(DATA_DIR, "promocodes.txt")